---


# Repositorio do Visual Studio Code

- name: Importando a chave do repositorio do Visual Studio Code
  apt_key: 
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: true
  tags:
    - repo
    - vscode

- name: Adicionando o Repositorio do Visual Studio Code
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode
  become: true
  tags:
    - repo
    - vscode

- name: "Atualizando apt cache"
  apt: 
    update_cache: yes 
    cache_valid_time: 7200
  become: true
  tags:
    - repo

# Instalação do Visual Studio Code

- name: Instalando o Visual Studio Code
  apt:
    name: code
    state: present
  become: true
  tags:
    - vscode